BOT_TOKEN = "8568797215:AAErQo4EwvOFAGuxqzIsVBn5Ll8zzFu4qBU"
ADMIN_PASSWORD = "admin123"
ADMIN_IDS = []
DATABASE_NAME = "event_bot.db"
ADMIN_CONTACT_EMAIL = "admin@example.com"
TELEGRAM_STORAGE_CHAT_ID = None
