# texts.py
# Все тексты бота на трёх языках

TEXTS = {
    'en': {
        # Начальные сообщения
        'choose_language': '🌍 Please choose your language:',
        'welcome': '👋 Welcome to Event Companion Bot!\n\n'
                  'Here you can find information about events and meetings.',
        
        # Главное меню
        'main_menu': '📋 Main Menu',
        'select_meeting': '📅 Select Meeting',
        'my_profile': '👤 My Profile',
        'edit_profile': '✏️ Edit Profile',
        'change_language': '🌍 Change Language',
        
        # Детали встречи
        'meeting_details': '📅 Meeting: {name}\n'
                          '📍 Location: {location}\n'
                          '📆 Date: {date}',
        'agenda': '📋 Agenda',
        'live_map': '🗺 Live Map',
        'photos': '📸 Photos',
        'people': '👥 People',
        'pdf_info': '📄 PDF Info',
        'follow': '✅ Follow',
        'unfollow': '❌ Unfollow',
        'qna': '❓ Q&A',
        'wifi': '📶 WiFi Password',
        'alerts': '🔔 Alerts',
        'back': '⬅️ Back',
        'next': '➡️ Next',
        'prev': '⬅️ Previous',
        'view_meeting': '👁️ View meeting',
        'fill_profile_first': '❌ Please fill your profile first to register.',
        'no_agenda_user': '📋 No items yet.',
        'no_photos_user': '📸 No photos yet.',
        'no_pdf_user': '📄 No PDF file yet.',
        'no_participants': '👥 No participants yet.',
        'satisfaction_prompt': 'Are you satisfied with the meeting?',
        'thank_you': '🙏 Thank you for participating!',
        
        # Профиль
        'fill_profile': '✏️ Fill your data:',
        'enter_name': 'Enter your name:',
        'enter_phone': 'Enter your phone number:',
        'enter_company': 'Enter your company:',
        'profile_saved': '✅ Data is updated!',
        'your_profile': '👤 Your Profile:\n\n'
                       'Name: {name}\n'
                       'Phone: {phone}\n'
                       'Company: {company}',
        
        # Q&A
        'ask_question': '❓ Ask your question (anonymous):',
        'question_sent': '✅ Your question has been sent!',
        'feedback_prompt': 'Do you want to share detailed feedback?',
        'yes': '✅ Yes',
        'no': '❌ No',
        'enter_feedback': 'Please enter your feedback:',
        'feedback_sent': '✅ Thank you for your feedback!',
        
        # WiFi
        'wifi_info': '📶 WiFi Password:\n\n'
                    'Network: {network}\n'
                    'Password: {password}',
        'add_wifi': '➕ Add WiFi',
        'edit_wifi_name': '✏️ Edit WiFi name',
        'edit_wifi_password': '✏️ Edit WiFi password',
        
        # Админка
        'admin_login': '🔐 Enter admin password:',
        'wrong_password': '❌ Wrong password!',
        'admin_welcome': '👑 Admin Panel',
        'add_meeting': '➕ Add Meeting',
        'manage_meetings': '📅 Manage Meetings',
        'view_questions': '❓ View Q&A',
        'send_notification': '📢 Send Notification',
        'send_all_users': '📢 Send to all users',
        'finish_meeting': '✅ Finish meeting',
        'set_deadline': '⏱ Set deadline',
        'confirm_finish_meeting': 'Are you sure you want to finish the meeting?',
        'deadline_set': '✅ Deadline set!',
        'choose_year': 'Select year:',
        'choose_month': 'Select month:',
        'choose_day': 'Select day:',
        'choose_hour': 'Select hour:',
        'choose_minute': 'Select minute:',
        'send_all_users': '📢 Send to all users',
        'exit_admin': '🚪 Exit Admin',
        'view_feedback': '💬 Feedback',
        'existing_meetings': '📅 Existing meetings',
        'finished_meetings': '✅ Finished meetings',
        'choose_action': '⚙️ Choose action:',
        
        # Создание встречи
        'enter_meeting_name': 'Enter meeting name:',
        'enter_location': 'Enter location:',
        'enter_date': 'Enter date (DD.MM.YYYY):',
        'meeting_created': '✅ Meeting created successfully!',
        'no_questions': '❓ No questions yet.',
        
        # Ошибки
        'no_meetings': '❌ No meetings available yet.',
        'error': '❌ An error occurred. Please try again.',
        'edit': '✏️ Edit',
        'delete': '🗑 Delete',
        'add': '➕ Add',
        'clear': '🧹 Clear',
        'no_wifi_info': '📶 WiFi info is not set yet.',
        'enter_wifi_name': 'Enter WiFi network name:',
        'enter_wifi_password': 'Enter WiFi password:',
        'wifi_added': '✅ WiFi updated!',
        'wifi_updated': '✅ WiFi updated!',
        'wifi_cleared': '🧹 WiFi info cleared.',
        'send_photos': 'Send one or more photos for this meeting.',
        'photo_added': '✅ Photo added!',
        'photos_cleared': '🧹 All photos cleared.',
        'no_photos_admin': '📸 No photos yet.',
        'no_pdf_admin': '📄 No PDF yet.',
        'add_pdf': '➕ Add PDF',
        'edit_pdf': '✏️ Edit PDF',
        'invalid_photo_format': '❌ Please send photos only.',
        'enter_notification': 'Enter notification text to send to all users:',
        'notification_sent': '📢 Notification sent.',
        'enter_geo_admin': 'Send a location to set for the meeting.',
        'geo_added': '✅ Location updated!',
        'geo_cleared': '🧹 Location cleared.',
        'geo_not_set': '🗺 Location is not set yet.',
        'send_pdf': 'Send a PDF document for this meeting.',
        'invalid_pdf_format': '❌ Please send a PDF file.',
        'pdf_added': '✅ PDF added!',
        'pdf_updated': '✅ PDF updated!',
        'pdf_deleted': '🗑 PDF deleted.',
        'confirm_delete_pdf': 'Are you sure you want to delete the PDF?',
        'enter_agenda_time': 'Enter agenda item time (e.g., 10:00):',
        'enter_agenda_description': 'Enter agenda item description:',
        'agenda_added': '✅ Agenda item added!',
        'alert': '🔔 Alert',
        'alert_on': '✅ Subscribed to alerts.',
        'alert_off': '❌ Unsubscribed from alerts.',
        'no_alert_subscribers': '👥 No subscribers yet.',
        'agenda_title': '✏️ Enter agenda title:',
        'agenda_start_time': '🕐 Enter start time (e.g., 10:00):',
        'agenda_end_time': '🕐 Enter end time (e.g., 11:00):',
        'agenda_description_optional': '📝 Enter description (optional):',
        'skip': '⏭ Skip',
        'delete_agenda_confirm': 'Are you sure to delete this agenda?',
        'agenda_item_deleted': '🗑 Agenda item deleted.',
        'edit_agenda': '✏️ Edit agenda',
        'edit_agenda_title': '✏️ Edit title',
        'edit_agenda_start': '🕐 Edit start time',
        'edit_agenda_end': '🕐 Edit end time',
        'edit_agenda_desc': '📝 Edit description',
        'agenda_cleared': '🧹 Agenda cleared.',
        'confirm_delete_meeting': 'Are you sure you want to delete the meeting?',
        'meeting_deleted': '🗑 Meeting deleted.',
        'no_agenda_admin': '📋 No items yet.',
        'fill_profile_button': '✏️ Fill Profile',
        'edit_name_button': '✏️ Edit Name',
        'edit_phone_button': '📞 Edit Phone',
        'edit_company_button': '🏢 Edit Company',
        'send_contact_button': '📱 Send contact',
        'meeting_updated': '✅ Meeting updated!',
        'edit_meeting_name': '✏️ Edit meeting name',
        'edit_meeting_date': '📆 Edit date',
        'edit_meeting_location': '📍 Edit location',
        'admin_wifi': '📶 WiFi',
        'admin_photos': '📸 Photos',
        'admin_geo': '🗺 Location',
        'admin_agenda': '📋 Agenda',
        'admin_pdf': '📄 PDF',
        'admin_finish_meeting': '✅ Finish meeting',
        'admin_delete_meeting': '🗑 Delete meeting'
        },
    
    'ru': {
        # Начальные сообщения
        'choose_language': '🌍 Пожалуйста, выберите язык:',
        'welcome': '👋 Добро пожаловать в Event Companion Bot!\n\n'
                  'Здесь вы можете найти информацию о мероприятиях и встречах.',
        
        # Главное меню
        'main_menu': '📋 Главное меню',
        'select_meeting': '📅 Выбрать встречу',
        'my_profile': '👤 Мой профиль',
        'edit_profile': '✏️ Редактировать профиль',
        'change_language': '🌍 Сменить язык',
        
        # Детали встречи
        'meeting_details': '📅 Встреча: {name}\n'
                          '📍 Место: {location}\n'
                          '📆 Дата: {date}',
        'agenda': '📋 Повестка дня',
        'live_map': '🗺 Карта',
        'photos': '📸 Фотографии',
        'people': '👥 Участники',
        'pdf_info': '📄 PDF информация',
        'follow': '✅ Подписаться',
        'unfollow': '❌ Отписаться',
        'qna': '❓ Вопросы и ответы',
        'wifi': '📶 Пароль WiFi',
        'alerts': '🔔 Уведомления',
        'back': '⬅️ Назад',
        'next': '➡️ Далее',
        'prev': '⬅️ Назад',
        'view_meeting': '👁️ Посмотреть встречу',
        'fill_profile_first': '❌ Сначала заполните профиль, чтобы зарегистрироваться.',
        'no_agenda_user': '📋 Пока нет пунктов.',
        'no_photos_user': '📸 Пока нет фотографий.',
        'no_pdf_user': '📄 Пока нет PDF файла.',
        'no_participants': '👥 Пока нет участников.',
        'satisfaction_prompt': 'Вы довольны встречей?',
        'thank_you': '🙏 Спасибо за участие!',
        
        # Профиль
        'fill_profile': '✏️ Заполните свои данные:',
        'enter_name': 'Введите ваше имя:',
        'enter_phone': 'Введите ваш номер телефона:',
        'enter_company': 'Введите вашу компанию:',
        'profile_saved': '✅ Данные обновлены!',
        'your_profile': '👤 Ваш профиль:\n\n'
                       'Имя: {name}\n'
                       'Телефон: {phone}\n'
                       'Компания: {company}',
        
        # Q&A
        'ask_question': '❓ Задайте ваш вопрос (анонимно):',
        'question_sent': '✅ Ваш вопрос отправлен!',
        'feedback_prompt': 'Хотите оставить подробный отзыв?',
        'yes': '✅ Да',
        'no': '❌ Нет',
        'enter_feedback': 'Пожалуйста, введите ваш отзыв:',
        'feedback_sent': '✅ Спасибо за ваш отзыв!',
        
        # WiFi
        'wifi_info': '📶 Пароль WiFi:\n\n'
                    'Сеть: {network}\n'
                    'Пароль: {password}',
        'add_wifi': '➕ Добавить WiFi',
        'edit_wifi_name': '✏️ Редактировать имя WiFi',
        'edit_wifi_password': '✏️ Редактировать пароль WiFi',
        
        # Админка
        'admin_login': '🔐 Введите пароль администратора:',
        'wrong_password': '❌ Неверный пароль!',
        'admin_welcome': '👑 Панель администратора',
        'add_meeting': '➕ Добавить встречу',
        'manage_meetings': '📅 Управление встречами',
        'view_questions': '❓ Просмотр вопросов',
        'send_notification': '📢 Отправить уведомление',
        'send_all_users': '📢 Отправить всем пользователям',
        'finish_meeting': '✅ Завершить встречу',
        'set_deadline': '⏱ Поставить дедлайн',
        'confirm_finish_meeting': 'Вы уверены, что хотите завершить встречу?',
        'deadline_set': '✅ Дедлайн установлен!',
        'choose_year': 'Выберите год:',
        'choose_month': 'Выберите месяц:',
        'choose_day': 'Выберите день:',
        'choose_hour': 'Выберите час:',
        'choose_minute': 'Выберите минуту:',
        'send_all_users': '📢 Отправить всем пользователям',
        'exit_admin': '🚪 Выйти',
        'view_feedback': '💬 Отзывы',
        'existing_meetings': '📅 Существующие встречи',
        'finished_meetings': '✅ Завершённые встречи',
        'choose_action': '⚙️ Выберите действие:',
        
        # Создание встречи
        'enter_meeting_name': 'Введите название встречи:',
        'enter_location': 'Введите место проведения:',
        'enter_date': 'Введите дату (ДД.ММ.ГГГГ):',
        'meeting_created': '✅ Встреча успешно создана!',
        'no_questions': '❓ Пока нет вопросов.',
        
        # Ошибки
        'no_meetings': '❌ Встречи пока не доступны.',
        'error': '❌ Произошла ошибка. Попробуйте снова.',
        'edit': '✏️ Редактировать',
        'delete': '🗑 Удалить',
        'add': '➕ Добавить',
        'clear': '🧹 Очистить',
        'no_wifi_info': '📶 Информация WiFi пока не задана.',
        'enter_wifi_name': 'Введите имя сети WiFi:',
        'enter_wifi_password': 'Введите пароль WiFi:',
        'wifi_added': '✅ WiFi обновлён!',
        'wifi_updated': '✅ WiFi обновлён!',
        'wifi_cleared': '🧹 WiFi очищен.',
        'send_photos': 'Отправьте одно или несколько фото для встречи.',
        'photo_added': '✅ Фото добавлено!',
        'photos_cleared': '🧹 Фото очищены.',
        'no_photos_admin': '📸 Пока нет фотографий.',
        'no_pdf_admin': '📄 Пока нет PDF.',
        'add_pdf': '➕ Добавить PDF',
        'edit_pdf': '✏️ Редактировать PDF',
        'invalid_photo_format': '❌ Пожалуйста, отправьте только фотографии.',
        'enter_notification': 'Введите текст уведомления для отправки всем пользователям:',
        'notification_sent': '📢 Уведомление отправлено.',
        'enter_geo_admin': 'Отправьте геолокацию для назначения встрече.',
        'geo_added': '✅ Геолокация обновлена!',
        'geo_cleared': '🧹 Геолокация очищена.',
        'geo_not_set': '🗺 Геолокация пока не задана.',
        'send_pdf': 'Отправьте PDF документ для встречи.',
        'invalid_pdf_format': '❌ Пожалуйста, отправьте PDF файл.',
        'pdf_added': '✅ PDF добавлен!',
        'pdf_updated': '✅ PDF обновлён!',
        'pdf_deleted': '🗑 PDF удалён.',
        'confirm_delete_pdf': 'Вы уверены, что хотите удалить PDF файл?',
        'enter_agenda_time': 'Введите время пункта повестки (например, 10:00):',
        'enter_agenda_description': 'Введите описание пункта повестки:',
        'agenda_added': '✅ Пункт повестки добавлен!',
        'alert': '🔔 Alert',
        'alert_on': '✅ Подписка на уведомления оформлена.',
        'alert_off': '❌ Подписка отменена.',
        'no_alert_subscribers': '👥 Подписчиков пока нет.',
        'agenda_title': '✏️ Введите название пункта:',
        'agenda_start_time': '🕐 Введите время начала (например, 10:00):',
        'agenda_end_time': '🕐 Введите время окончания (например, 11:00):',
        'agenda_description_optional': '📝 Введите описание (по желанию):',
        'skip': '⏭ Пропустить',
        'delete_agenda_confirm': 'Вы уверены, что хотите удалить этот пункт?',
        'agenda_item_deleted': '🗑 Пункт повестки удалён.',
        'edit_agenda': '✏️ Редактировать пункт',
        'edit_agenda_title': '✏️ Редактировать название',
        'edit_agenda_start': '🕐 Редактировать время начала',
        'edit_agenda_end': '🕐 Редактировать время окончания',
        'edit_agenda_desc': '📝 Редактировать описание',
        'agenda_cleared': '🧹 Повестка очищена.',
        'confirm_delete_meeting': 'Удалить встречу? Подтвердите действие.',
        'meeting_deleted': '🗑 Встреча удалена.',
        'no_agenda_admin': '📋 Пока нет пунктов.',
        'fill_profile_button': '✏️ Заполнить профиль',
        'edit_name_button': '✏️ Редактировать имя',
        'edit_phone_button': '📞 Редактировать телефон',
        'edit_company_button': '🏢 Редактировать компанию',
        'send_contact_button': '📱 Отправить контакт',
        'meeting_updated': '✅ Встреча обновлена!',
        'edit_meeting_name': '✏️ Редактировать название',
        'edit_meeting_date': '📆 Редактировать дату',
        'edit_meeting_location': '📍 Редактировать локацию',
        'admin_wifi': '📶 WiFi',
        'admin_photos': '📸 Фото',
        'admin_geo': '🗺 Локация',
        'admin_agenda': '📋 Повестка дня',
        'admin_pdf': '📄 PDF',
        'admin_finish_meeting': '✅ Завершить встречу',
        'admin_delete_meeting': '🗑 Удалить встречу'
        },
    
    'uz': {
        # Начальные сообщения
        'choose_language': '🌍 Iltimos, tilni tanlang:',
        'welcome': '👋 Event Companion Botiga xush kelibsiz!\n\n'
                  'Bu yerda tadbirlar va uchrashuvlar haqida ma\'lumot olishingiz mumkin.',
        
        # Главное меню
        'main_menu': '📋 Asosiy menyu',
        'select_meeting': '📅 Uchrashuvni tanlash',
        'my_profile': '👤 Mening profilim',
        'edit_profile': '✏️ Profilni tahrirlash',
        'change_language': '🌍 Tilni o\'zgartirish',
        
        # Детали встречи
        'meeting_details': '📅 Uchrashuv: {name}\n'
                          '📍 Manzil: {location}\n'
                          '📆 Sana: {date}',
        'agenda': '📋 Kun tartibi',
        'live_map': '🗺 Xarita',
        'photos': '📸 Rasmlar',
        'people': '👥 Ishtirokchilar',
        'pdf_info': '📄 PDF maʼlumot',
        'follow': '✅ Obuna bo\'lish',
        'unfollow': '❌ Obunani bekor qilish',
        'qna': '❓ Savol-javob',
        'wifi': '📶 WiFi paroli',
        'alerts': '🔔 Bildirishnomalar',
        'back': '⬅️ Orqaga',
        'next': '➡️ Keyingi',
        'prev': '⬅️ Oldingi',
        'view_meeting': '👁️ Uchrashuvni ko‘rish',
        'fill_profile_first': '❌ Ro‘yxatdan o‘tish uchun avval profilingizni to‘ldiring.',
        'no_agenda_user': '📋 Hozircha bandlar yo‘q.',
        'no_photos_user': '📸 Hozircha rasmlar yo‘q.',
        'no_pdf_user': '📄 Hozircha PDF mavjud emas.',
        'no_participants': '👥 Hozircha ishtirokchilar yo‘q.',
        'satisfaction_prompt': 'Uchrashuvdan mamnunmisiz?',
        'thank_you': '🙏 Ishtirok etganingiz uchun rahmat!',
        
        # Профиль
        'fill_profile': '✏️ Ma\'lumotlaringizni kiriting:',
        'enter_name': 'Ismingizni kiriting:',
        'enter_phone': 'Telefon raqamingizni kiriting:',
        'enter_company': 'Kompaniyangizni kiriting:',
        'profile_saved': '✅ Ma\'lumotlar yangilandi!',
        'your_profile': '👤 Sizning profilingiz:\n\n'
                       'Ism: {name}\n'
                       'Telefon: {phone}\n'
                       'Kompaniya: {company}',
        
        # Q&A
        'ask_question': '❓ Savolingizni yozing (anonim):',
        'question_sent': '✅ Savolingiz yuborildi!',
        'feedback_prompt': 'Batafsil fikr-mulohaza qoldirmoqchimisiz?',
        'yes': '✅ Ha',
        'no': '❌ Yo\'q',
        'enter_feedback': 'Iltimos, fikr-mulohazangizni kiriting:',
        'feedback_sent': '✅ Fikr-mulohazangiz uchun rahmat!',
        
        # WiFi
        'wifi_info': '📶 WiFi paroli:\n\n'
                    'Tarmoq: {network}\n'
                    'Parol: {password}',
        'add_wifi': '➕ WiFi qo\'shish',
        'edit_wifi_name': '✏️ WiFi nomini tahrirlash',
        'edit_wifi_password': '✏️ WiFi parolini tahrirlash',
        
        # Админка
        'admin_login': '🔐 Administrator parolini kiriting:',
        'wrong_password': '❌ Noto\'g\'ri parol!',
        'admin_welcome': '👑 Administrator paneli',
        'add_meeting': '➕ Uchrashuv qo\'shish',
        'manage_meetings': '📅 Uchrashuvlarni boshqarish',
        'view_questions': '❓ Savollarni ko\'rish',
        'send_notification': '📢 Xabar yuborish',
        'send_all_users': '📢 Barcha foydalanuvchilarga yuborish',
        'finish_meeting': '✅ Uchrashuvni yakunlash',
        'set_deadline': '⏱ Muddat belgilash',
        'confirm_finish_meeting': 'Uchrashuvni yakunlashni tasdiqlaysizmi?',
        'deadline_set': '✅ Muddat belgilandi!',
        'choose_year': 'Yilni tanlang:',
        'choose_month': 'Oyni tanlang:',
        'choose_day': 'Kunni tanlang:',
        'choose_hour': 'Soatni tanlang:',
        'choose_minute': 'Daqiqani tanlang:',
        'send_all_users': '📢 Barcha foydalanuvchilarga yuborish',
        'exit_admin': '🚪 Chiqish',
        'view_feedback': '💬 Fikrlar',
        'existing_meetings': '📅 Mavjud uchrashuvlar',
        'finished_meetings': '✅ Yakunlangan uchrashuvlar',
        'choose_action': '⚙️ Amalni tanlang:',
        
        # Создание встречи
        'enter_meeting_name': 'Uchrashuv nomini kiriting:',
        'enter_location': 'Manzilni kiriting:',
        'enter_date': 'Sanani kiriting (KK.OO.YYYY):',
        'meeting_created': '✅ Uchrashuv muvaffaqiyatli yaratildi!',
        'no_questions': '❓ Hozircha savollar yoʻq.',
        
        # Ошибки
        'no_meetings': '❌ Hozircha uchrashuvlar mavjud emas.',
        'error': '❌ Xatolik yuz berdi. Qaytadan urinib ko\'ring.',
        'edit': '✏️ Tahrirlash',
        'delete': '🗑 O\'chirish',
        'add': '➕ Qo\'shish',
        'clear': '🧹 Tozalash',
        'no_wifi_info': '📶 WiFi ma\'lumoti hali o\'rnatilmagan.',
        'enter_wifi_name': 'WiFi tarmoq nomini kiriting:',
        'enter_wifi_password': 'WiFi parolini kiriting:',
        'wifi_added': '✅ WiFi yangilandi!',
        'wifi_updated': '✅ WiFi yangilandi!',
        'wifi_cleared': '🧹 WiFi tozalandi.',
        'send_photos': 'Uchrashuv uchun bir yoki bir nechta rasm yuboring.',
        'photo_added': '✅ Rasm qo\'shildi!',
        'photos_cleared': '🧹 Rasmlar tozalandi.',
        'no_photos_admin': '📸 Hozircha rasmlar yo\'q.',
        'no_pdf_admin': '📄 Hozircha PDF yo\'q.',
        'add_pdf': '➕ PDF qo\'shish',
        'edit_pdf': '✏️ PDFni tahrirlash',
        'invalid_photo_format': '❌ Iltimos, faqat rasmlar yuboring.',
        'enter_notification': 'Barcha foydalanuvchilarga xabar matnini kiriting:',
        'notification_sent': '📢 Xabar yuborildi.',
        'enter_geo_admin': 'Uchrashuv uchun joylashuv yuboring.',
        'geo_added': '✅ Joylashuv yangilandi!',
        'geo_cleared': '🧹 Joylashuv tozalandi.',
        'geo_not_set': '🗺 Joylashuv hali o\'rnatilmagan.',
        'send_pdf': 'Uchrashuv uchun PDF hujjat yuboring.',
        'invalid_pdf_format': '❌ Faqat PDF fayl yuboring.',
        'pdf_added': '✅ PDF qo‘shildi!',
        'pdf_updated': '✅ PDF yangilandi!',
        'pdf_deleted': '🗑 PDF o‘chirildi.',
        'confirm_delete_pdf': 'PDF faylni o‘chirishni tasdiqlaysizmi?',
        'enter_agenda_time': 'Kun tartibi vaqti (masalan, 10:00) ni kiriting:',
        'enter_agenda_description': 'Kun tartibi tavsifini kiriting:',
        'agenda_added': '✅ Kun tartibi bandi qo\'shildi!',
        'alert': '🔔 Alert',
        'alert_on': '✅ Bildirishnomalarga obuna bo\'lindi.',
        'alert_off': '❌ Obuna bekor qilindi.',
        'no_alert_subscribers': '👥 Hozircha obunachilar yo\'q.',
        'agenda_title': '✏️ Band nomini kiriting:',
        'agenda_start_time': '🕐 Boshlanish vaqtini kiriting (masalan, 10:00):',
        'agenda_end_time': '🕐 Tugash vaqtini kiriting (masalan, 11:00):',
        'agenda_description_optional': '📝 Tavsifni kiriting (ixtiyoriy):',
        'skip': '⏭ O\'tkazib yuborish',
        'delete_agenda_confirm': 'Ushbu bandni o\'chirishni tasdiqlaysizmi?',
        'agenda_item_deleted': '🗑 Band o\'chirildi.',
        'edit_agenda': '✏️ Bandni tahrirlash',
        'edit_agenda_title': '✏️ Sarlavhani tahrirlash',
        'edit_agenda_start': '🕐 Boshlanish vaqtini tahrirlash',
        'edit_agenda_end': '🕐 Tugash vaqtini tahrirlash',
        'edit_agenda_desc': '📝 Tavsifni tahrirlash',
        'agenda_cleared': '🧹 Kun tartibi tozalandi.',
        'confirm_delete_meeting': 'Uchrashuvni o\'chirishni tasdiqlaysizmi?',
        'meeting_deleted': '🗑 Uchrashuv o\'chirildi.',
        'no_agenda_admin': '📋 Hozircha bandlar yo‘q.',
        'fill_profile_button': '✏️ Profilni to‘ldirish',
        'edit_name_button': '✏️ Ismni tahrirlash',
        'edit_phone_button': '📞 Telefonni tahrirlash',
        'edit_company_button': '🏢 Kompaniyani tahrirlash',
        'send_contact_button': '📱 Kontakt yuborish',
        'meeting_updated': '✅ Uchrashuv yangilandi!',
        'edit_meeting_name': '✏️ Uchrashuv nomini tahrirlash',
        'edit_meeting_date': '📆 Sanani tahrirlash',
        'edit_meeting_location': '📍 Manzilni tahrirlash',
        'admin_wifi': '📶 WiFi',
        'admin_photos': '📸 Rasmlar',
        'admin_geo': '🗺 Joylashuv',
        'admin_agenda': '📋 Kun tartibi',
        'admin_pdf': '📄 PDF',
        'admin_finish_meeting': '✅ Uchrashuvni yakunlash',
        'admin_delete_meeting': '🗑 Uchrashuvni o‘chirish'
        }
}

# Языки
LANGUAGES = {
    'en': '🇬🇧 English',
    'ru': '🇷🇺 Русский',
    'uz': '🇺🇿 O\'zbekcha'
}

def get_text(lang, key, **kwargs):
    """Получить текст на нужном языке"""
    text = TEXTS.get(lang, TEXTS['en']).get(key, key)
    if kwargs:
        return text.format(**kwargs)
    return text
